Add Systemd to upgrade.sh and fix Systemd environment variables.
WhitewaterFoundry/fedora-remix-rootfs-build pull request #19
Opened 2022-04-02 21:22 UTC by carrizo

2022-04-02 22:01 UTC, crramirez requested changes

2022-04-02 22:01 UTC, crramirez commented on linux_files/upgrade.sh
> +sudo chmod u+x /usr/local/bin/wslsystemctl
Make it executable for every user so bash-completion will show it with sudo
```suggestion
sudo chmod +x /usr/local/bin/wslsystemctl
```

2022-04-02 22:01 UTC, crramirez commented on linux_files/00-remix.sh
> +if [ ! -f "$HOME/.systemd.env" ]
Formatting
```suggestion
if [ ! -f "$HOME/.systemd.env" ]; then
```

2022-04-02 22:01 UTC, crramirez commented on linux_files/00-remix.sh
> +then
```suggestion
```

2022-04-02 22:01 UTC, crramirez commented on linux_files/00-remix.sh
> +    echo "PATH='$PATH'" > "$HOME/.systemd.env"
```suggestion
  echo "PATH='$PATH'" > "$HOME/.systemd.env"
```

2022-04-02 22:01 UTC, crramirez commented on create-targz.sh
>    chmod -x "${TMPDIR}"/dist/etc/fish/conf.d/00-remix.fish
Probably it should be needed also for fish
```suggestion
  chmod -x,+r "${TMPDIR}"/dist/etc/fish/conf.d/00-remix.fish
```

2022-04-02 22:01 UTC, crramirez commented on create-targz.sh
>  chmod -x /etc/fish/conf.d/check-dnf.fish
```suggestion
chmod -x,+r /etc/fish/conf.d/check-dnf.fish
```

2022-04-02 22:01 UTC, crramirez commented on linux_files/00-remix.sh
> +else
You can use `elif`

2022-04-03 18:14 UTC, carrizo commented on linux_files/00-remix.sh
> +else
fixed

2022-04-03 21:06 UTC, crramirez approved these changes

2022-04-03 21:06 UTC, merged